name: Test Github Workflow

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/*.yaml"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Test-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        run: echo "Hello GitHub Actions!"
  second-job:
    runs-on: windows-latest
    needs: Test-jobs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Goodbye
        run: echo "This job is running on ${{ runner.os }} and it depends on the first job."