name: Test Hello World Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello World
        run: echo "Running on ubuntu-latest"

  Second-job:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Windows
        run: echo "Running on Windows"