name: Test Github Workflow

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/*.yaml"

  pull_request:
    branches: [main]

  repository_dispatch:
    types: ["on-demand-test"]

jobs:
  Test-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        run: echo "Hello GitHub Actions!"

      - name: Show Payload
        run: |
          echo "Status = ${{ github.event.client_payload.status }}"

  second-job:
    runs-on: windows-latest
    needs: Test-jobs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Windows
        run: echo "Running on Windows"