name: Workflow Dispatch Demo

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
      run_ui_tests:
        description: 'Run UI Tests'
        required: true
        default: 'false'
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.set_status.outputs.status }}
    steps:

      - name: Checkout
        uses: actions/checkout@v5
      - name: show inputs
        run: |
          echo "Target Environment = ${{ github.event.inputs.env }}"
          echo "Run UI Tests = ${{ github.event.inputs.run_ui_tests }}"
      - name: set an output status
        id: set_status
        run: echo "status=success" >> $GITHUB_OUTPUT
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: UI Tests
        if: ${{ github.event.inputs.run_ui_tests == 'true' }}
        run: |
           echo "the build status is ${{ needs.build.outputs.build_status }}"
           echo "Running UI Tests on ${{ github.event.inputs.env }} environment"