name: Workflow Dispatch Demo

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
      run_ui_tests:
        description: 'Run UI Tests'
        required: true
        default: 'false'
        type: boolean
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: show inputs
        run: |
          echo "Target Environment = ${{ github.event.inputs.env }}"
          echo "Run UI Tests = ${{ github.event.inputs.run_ui_tests }}"
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: UI Tests
        if: ${{ github.event.inputs.run_ui_tests == 'true' }}
        run: echo "Running UI Tests on ${{ github.event.inputs.env }} environment"